# Site settings
title: WIll Morris | Creative Web Developer
description:
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Will Morris
user_description: I specializes in making things for human people. By day I let his mind wander the highways and biways of the creative world. By night I write those thoughts out in code.
user_title: Creative Web Developer
email: Will@willmorr.is
twitter_username:
github_username: thesnowman
gplus_username:

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
